name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Push to build branch
      run: |
        git config --global user.name "Gavin White"
        git config --global user.email "gavinwhite0314@gmail.com"
        git checkout -b build
        git add .
        git commit -m "Build assets"
        git push origin build


