name: Generate a build and deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Push to Hostinger
        run: |
          git config --global user.name "Gavin White"
          git config --global user.email "gavinwhite0314@gmail.com"
          git remote add hostinger <your-hostinger-git-repository-url>
          git push hostinger build
